server:
  port: 8088
#  servlet 上下文路径 默认/ 可以通过此方式设置上下文访问路径
  servlet:
    context-path: /im_bird_sys
spring:
  datasource:
    name: im_bird_sys
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.200.79.231:3306/im_bird
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 802300
#    监控统计
    filters: stat
    initial-size: 2     # 初始化连接
    max-idle: 10        # 最大空闲连接数
    min-idle: 1         # 最小空闲连接数
    max-active: 20     #  最大活动连接数
    max-wait: 60000     #  获取连接超时的等待时间
    time-between-evict-runs-millis: 60000   #  间隔多久进行一次检测 检测需要关闭的空闲连接
    min-evictable-time-millis: 300000       #  一个连接在池中最小生存时间
    validation-query: SELECT 'x'            #  检验连接有效与否的sql
    test-while-idle: true
    test-on-borrow: false
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 172.17.9.194:22122
